/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author gediez
 */
public class RadioBtn extends JPanel implements ActionListener{

    /**
     * Creates new form ChosseRadioBtn
     */
    public RadioBtn() {        
        initComponents();
        lista = new ArrayList();
        titulo = new JLabel("<<ChosseRadioBtn>>");
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoRB = new javax.swing.ButtonGroup();

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setTitulo(String t){
        titulo.setText(t);
    }
    
    public void removerOpciones(){
        Iterator<JRadioButton> itera = lista.iterator();
        while(itera.hasNext()){
            JRadioButton jrb = itera.next();
            GrupoRB.remove(jrb);
            remove(jrb);
        }
    }
    
    public void setOpciones(String[] ops){
        removerOpciones();
        if(ops.length >= 2){
            opciones = ops;
            lista.clear();            
            int i = 0;
            while(i < ops.length){
                JRadioButton rb = new JRadioButton();
                rb.setText(ops[i]);
                rb.addActionListener(this);
                lista.add(rb);
                i++;
            }
            Iterator<JRadioButton> itera = lista.iterator();
            while(itera.hasNext()){
                JRadioButton jrb = itera.next();
                add(jrb);
                GrupoRB.add(jrb);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Deben de ser dos o mas opciones", "WARNING",JOptionPane.WARNING_MESSAGE);
        }
        
    }
    
    public String[] getOpciones(){
        return opciones;
    }
    
    public String getSeleccionado(){
        return seleccionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoRB;
    // End of variables declaration//GEN-END:variables
    private String[] opciones;
    private ArrayList<JRadioButton> lista;
    private JLabel titulo;
    private String seleccionado = null;

    @Override
    public void actionPerformed(ActionEvent ae) {
        Iterator<JRadioButton> itera = lista.iterator();
        while(itera.hasNext()){
            JRadioButton jrb = itera.next();
            if(ae.getSource() == jrb){
                seleccionado = jrb.getText();
            }
        }
    }
}
